package com.ilsecondodasinistra.workitout.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pauseWorkingDaoConfig;
    private final DaoConfig sessionWorkingDaoConfig;

    private final PauseWorkingDao pauseWorkingDao;
    private final SessionWorkingDao sessionWorkingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pauseWorkingDaoConfig = daoConfigMap.get(PauseWorkingDao.class).clone();
        pauseWorkingDaoConfig.initIdentityScope(type);

        sessionWorkingDaoConfig = daoConfigMap.get(SessionWorkingDao.class).clone();
        sessionWorkingDaoConfig.initIdentityScope(type);

        pauseWorkingDao = new PauseWorkingDao(pauseWorkingDaoConfig, this);
        sessionWorkingDao = new SessionWorkingDao(sessionWorkingDaoConfig, this);

        registerDao(PauseWorking.class, pauseWorkingDao);
        registerDao(SessionWorking.class, sessionWorkingDao);
    }
    
    public void clear() {
        pauseWorkingDaoConfig.getIdentityScope().clear();
        sessionWorkingDaoConfig.getIdentityScope().clear();
    }

    public PauseWorkingDao getPauseWorkingDao() {
        return pauseWorkingDao;
    }

    public SessionWorkingDao getSessionWorkingDao() {
        return sessionWorkingDao;
    }

}
