package com.ilsecondodasinistra.workitout.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ilsecondodasinistra.workitout.database.Entity_PauseWorking;
import com.ilsecondodasinistra.workitout.database.Entity_SessionWorking;

import com.ilsecondodasinistra.workitout.database.Entity_PauseWorkingDao;
import com.ilsecondodasinistra.workitout.database.Entity_SessionWorkingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entity_PauseWorkingDaoConfig;
    private final DaoConfig entity_SessionWorkingDaoConfig;

    private final Entity_PauseWorkingDao entity_PauseWorkingDao;
    private final Entity_SessionWorkingDao entity_SessionWorkingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entity_PauseWorkingDaoConfig = daoConfigMap.get(Entity_PauseWorkingDao.class).clone();
        entity_PauseWorkingDaoConfig.initIdentityScope(type);

        entity_SessionWorkingDaoConfig = daoConfigMap.get(Entity_SessionWorkingDao.class).clone();
        entity_SessionWorkingDaoConfig.initIdentityScope(type);

        entity_PauseWorkingDao = new Entity_PauseWorkingDao(entity_PauseWorkingDaoConfig, this);
        entity_SessionWorkingDao = new Entity_SessionWorkingDao(entity_SessionWorkingDaoConfig, this);

        registerDao(Entity_PauseWorking.class, entity_PauseWorkingDao);
        registerDao(Entity_SessionWorking.class, entity_SessionWorkingDao);
    }
    
    public void clear() {
        entity_PauseWorkingDaoConfig.getIdentityScope().clear();
        entity_SessionWorkingDaoConfig.getIdentityScope().clear();
    }

    public Entity_PauseWorkingDao getEntity_PauseWorkingDao() {
        return entity_PauseWorkingDao;
    }

    public Entity_SessionWorkingDao getEntity_SessionWorkingDao() {
        return entity_SessionWorkingDao;
    }

}
