package com.ilsecondodasinistra.workitout.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.ilsecondodasinistra.workitout.classes.SuperPauseWorking;

/**
 * Entity mapped to table PausesWorking.
 */
public class Entity_PauseWorking extends SuperPauseWorking implements java.io.Serializable {

//    protected Long id;
    /** Not-null value. */
//    protected java.util.Date startDate;
    /** Not-null value. */
//    protected java.util.Date endDate;
//    protected boolean isLunch;
//    protected Long id_sessionworking;

    public Entity_PauseWorking() {
    }

    public Entity_PauseWorking(Long id) {
        this.id = id;
    }

    public Entity_PauseWorking(Long id, java.util.Date startDate, java.util.Date endDate, boolean isLunch, Long id_sessionworking) {
        this.id = id;
        this.startDate = startDate;
        this.endDate = endDate;
        this.isLunch = isLunch;
        this.id_sessionworking = id_sessionworking;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean getIsLunch() {
        return isLunch;
    }

    public void setIsLunch(boolean isLunch) {
        this.isLunch = isLunch;
    }

    public Long getId_sessionworking() {
        return id_sessionworking;
    }

    public void setId_sessionworking(Long id_sessionworking) {
        this.id_sessionworking = id_sessionworking;
    }

}
