package com.ilsecondodasinistra.workitout.database;

import com.ilsecondodasinistra.workitout.classes.SuperSessionWorking;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SessionsWorking.
 */
public class Entity_SessionWorking extends SuperSessionWorking implements java.io.Serializable {

//    protected Long id;
    /** Not-null value. */
//    protected java.util.Date entranceDate;
    /** Not-null value. */
//    protected java.util.Date exitDate;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient Entity_SessionWorkingDao myDao;

//    protected List<Entity_PauseWorking> pauses;

    public Entity_SessionWorking() {
    }

    public Entity_SessionWorking(Long id) {
        this.id = id;
    }

    public Entity_SessionWorking(Long id, java.util.Date entranceDate, java.util.Date exitDate) {
        this.id = id;
        this.entranceDate = entranceDate;
        this.exitDate = exitDate;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEntity_SessionWorkingDao() : null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Entity_PauseWorking> getPauses() {
        if (pauses == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            Entity_PauseWorkingDao targetDao = daoSession.getEntity_PauseWorkingDao();
            List<Entity_PauseWorking> pausesNew = targetDao._queryEntity_SessionWorking_Pauses(id);
            synchronized (this) {
                if(pauses == null) {
                    pauses = pausesNew;
                }
            }
        }
        return pauses;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPauses() {
        pauses = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
