package com.ilsecondodasinistra.workitout.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PausesWorking.
 */
public class Entity_PauseWorking extends com.ilsecondodasinistra.workitout.classes.PauseWorking  implements java.io.Serializable {

    protected int id_pauseworking;
    /** Not-null value. */
    protected java.util.Date start_date;
    /** Not-null value. */
    protected java.util.Date end_date;
    protected int id_sessionworking;

    public Entity_PauseWorking() {
    }

    public Entity_PauseWorking(int id_pauseworking) {
        this.id_pauseworking = id_pauseworking;
    }

    public Entity_PauseWorking(int id_pauseworking, java.util.Date start_date, java.util.Date end_date, int id_sessionworking) {
        this.id_pauseworking = id_pauseworking;
        this.start_date = start_date;
        this.end_date = end_date;
        this.id_sessionworking = id_sessionworking;
    }

    public int getId_pauseworking() {
        return id_pauseworking;
    }

    public void setId_pauseworking(int id_pauseworking) {
        this.id_pauseworking = id_pauseworking;
    }

    /** Not-null value. */
    public java.util.Date getStart_date() {
        return start_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStart_date(java.util.Date start_date) {
        this.start_date = start_date;
    }

    /** Not-null value. */
    public java.util.Date getEnd_date() {
        return end_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnd_date(java.util.Date end_date) {
        this.end_date = end_date;
    }

    public int getId_sessionworking() {
        return id_sessionworking;
    }

    public void setId_sessionworking(int id_sessionworking) {
        this.id_sessionworking = id_sessionworking;
    }

}
