package com.ilsecondodasinistra.workitout.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SessionsWorking.
*/
public class Entity_SessionWorkingDao extends AbstractDao<Entity_SessionWorking, Long> {

    public static final String TABLENAME = "SessionsWorking";

    /**
     * Properties of entity Entity_SessionWorking.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id_sessionworking");
        public final static Property EntranceDate = new Property(1, java.util.Date.class, "entranceDate", false, "ENTRANCE_DATE");
        public final static Property ExitDate = new Property(2, java.util.Date.class, "exitDate", false, "EXIT_DATE");
    };

    private DaoSession daoSession;


    public Entity_SessionWorkingDao(DaoConfig config) {
        super(config);
    }
    
    public Entity_SessionWorkingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SessionsWorking' (" + //
                "'id_sessionworking' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ENTRANCE_DATE' INTEGER NOT NULL ," + // 1: entranceDate
                "'EXIT_DATE' INTEGER NOT NULL );"); // 2: exitDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SessionsWorking'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Entity_SessionWorking entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEntranceDate().getTime());
        stmt.bindLong(3, entity.getExitDate().getTime());
    }

    @Override
    protected void attachEntity(Entity_SessionWorking entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Entity_SessionWorking readEntity(Cursor cursor, int offset) {
        Entity_SessionWorking entity = new Entity_SessionWorking( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // entranceDate
            new java.util.Date(cursor.getLong(offset + 2)) // exitDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Entity_SessionWorking entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEntranceDate(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setExitDate(new java.util.Date(cursor.getLong(offset + 2)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Entity_SessionWorking entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Entity_SessionWorking entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
