package com.ilsecondodasinistra.workitout.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table PausesWorking.
 */
public class PauseWorking extends com.ilsecondodasinistra.workitout.classes.SuperPauseWorking implements java.io.Serializable {

//    private Long id;
//    private long startDate;
//    private long endDate;
//    private boolean isLunch;
//    private Long id_sessionworking;

    public PauseWorking() {

    }

    public PauseWorking(Long id) {
        this.id = id;
    }

    public PauseWorking(Long id, long startDate, long endDate, boolean isLunch, Long id_sessionworking) {
        this.id = id;
        this.startDate = startDate;
        this.endDate = endDate;
        this.isLunch = isLunch;
        this.id_sessionworking = id_sessionworking;
    }

    public boolean getIsLunch() {
        return isLunch();
    }

}
