package com.ilsecondodasinistra.workitout.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SessionsWorking.
*/
public class SessionWorkingDao extends AbstractDao<SessionWorking, Long> {

    public static final String TABLENAME = "SessionsWorking";

    /**
     * Properties of entity SessionWorking.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id_sessionworking");
        public final static Property EntranceDate = new Property(1, long.class, "entranceDate", false, "ENTRANCE_DATE");
        public final static Property ExitDate = new Property(2, long.class, "exitDate", false, "EXIT_DATE");
    };

    private DaoSession daoSession;


    public SessionWorkingDao(DaoConfig config) {
        super(config);
    }
    
    public SessionWorkingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SessionsWorking' (" + //
                "'id_sessionworking' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ENTRANCE_DATE' INTEGER NOT NULL ," + // 1: entranceDate
                "'EXIT_DATE' INTEGER NOT NULL );"); // 2: exitDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SessionsWorking'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SessionWorking entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEntranceDate());
        stmt.bindLong(3, entity.getExitDate());
    }

    @Override
    protected void attachEntity(SessionWorking entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SessionWorking readEntity(Cursor cursor, int offset) {
        SessionWorking entity = new SessionWorking( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // entranceDate
            cursor.getLong(offset + 2) // exitDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SessionWorking entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEntranceDate(cursor.getLong(offset + 1));
        entity.setExitDate(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SessionWorking entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SessionWorking entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
